import React, { useContext, useState, useEffect, useRef } from "react";
import {
  addData,
  getAllData,
  getData,
  pagoTarjeta,
} from "../../Features/apiCalls";
import { CardElement, useElements, useStripe } from "@stripe/react-stripe-js";
import { UserContext } from "../../Contexts/UserContext";
import { Modal } from "react-bootstrap";
import easyinvoice from "easyinvoice";
import Swal from "sweetalert2";
import withReactContent from "sweetalert2-react-content";

const ReservaPopUp = ({ vehiculo, nombreProducto, ...props }) => {
  const userContext = useContext(UserContext);
  const stripe = useStripe();
  const elements = useElements();
  let contrato =
    "JVBERi0xLjMKJf////8KOCAwIG9iago8PAovVHlwZSAvRXh0R1N0YXRlCi9jYSAxCi9DQSAxCj4+CmVuZG9iago3IDAgb2JqCjw8Ci9UeXBlIC9QYWdlCi9QYXJlbnQgMSAwIFIKL01lZGlhQm94IFswIDAgNTk1LjI4IDg0MS44OV0KL0NvbnRlbnRzIDUgMCBSCi9SZXNvdXJjZXMgNiAwIFIKPj4KZW5kb2JqCjYgMCBvYmoKPDwKL1Byb2NTZXQgWy9QREYgL1RleHQgL0ltYWdlQiAvSW1hZ2VDIC9JbWFnZUldCi9FeHRHU3RhdGUgPDwKL0dzMSA4IDAgUgo+PgovRm9udCA8PAovRjEgOSAwIFIKL0YyIDEwIDAgUgo+Pgo+PgplbmRvYmoKNSAwIG9iago8PAovTGVuZ3RoIDY5NjEKL0ZpbHRlciAvRmxhdGVEZWNvZGUKPj4Kc3RyZWFtCniczV3LjlxHct3zK/oHlJMZEfkCBC4GtgfwzoZ2hhckmxx44QEGAvz9jsj76FvNqsiixHOrMGpx1GQzT0VGxvuRXqL+75ek/2qSQusvX/73w1/+9nt6+fvvH/7yL1//73++fP3Pv/315cvvH+L4o79/+ceHbx/++SFd+8G//rZ+P72kXoNwbr291JZD6rG29PKb/uX/pr/ZXn779uG/fo0xJv0i/eKPL0lCKjHl8mK/IfqV9at8fCkpZGLhtvyG/kkOpaZW8/iG/Xj9+BL/++W3f//wr799+I+f8gGoS2ikR7jwm351yPlMKRClmCcI8org0/pr/vjSA9XKIoM6nz++cAlF/6a+fKP8INSf8WEkUEukn4RzKIpTr3J8EnpJdMEKd3/9dHrr93ItpVYf5ODVI3tCwFQFw3pO8cHUAwcamE/6NLr+pJF63P3GD7Xksn6vQQAniqFW6r37iAVGssQ1tEatThCUw+UZfb7o1+v6/YpDp9JEX2CXyY2Wy9u8eMkYZERZv1nzBNjXw9cR5OcD+WT9/W8fX6SHFqW0IbLtwQKQc2wht5zLRK5scAEIqIREPeqxLgIlUkorkteVaBsBMbfKtYQaU4v+a9hR9UUy6DOOidf/3lBjJIZIC7FwEfIRyipwXzEoit5gbz1NUOzv8ShJP77UwCSU+uBys1QCi/2J/b2WAw31539RGbUKZ/tgoIehCiDoB+vdfxipYk7Xb5Zee5mwHvhi40sl06JNrp7elpMHsx/l2bjExrkv1ua4pf7z1UEMZtCadRnVTq75T1hEQHClc5DEVyn4KDMtuqjSJ7svDF+T2hf6uosPwKSm2hTJ2Fqdml+OIiN9fee72J+G3GAMEoV69a/w2/IE0zeQTSj6/roKeZ9ibaEDxXcuYFrtDVJohUI36y7dJCMR8iHUHjj/Gb8F8hA8VDjRqg+hJmlqlXoAfo7KxDCmXmyKVYh8EgKdFTW6i0Qji4ugvpllxNfoufzeQIkzJlMvoVeyS3LRYoQZxRIGh7B/utKC5IbbtDl2GH4iUR3e1d+pPsICe5KUlS2yOkP9Po42U7SF2lQ40/IQV1Oorr9ibH6OcpdEvXaFt6FfypSj24JyPFUbSaOZ/NidK1k58NNK3HNCMqLusbqAqU6k3EHGjDdEIHcvh1jLFM21qz/GGgDIag6Sp3TabxOAoKujYo93olGvaEtSutAq4aiu8qUtPAf1W0rJgdp15+rxfku22PlTOVVmrjmoqJ3ht3gA+uoLmAh4L2MJQxN1CkrqSZKPDOUjcWj6Zlh8dlHfiL68OSI5cN1SKYNW+uDo65IXwLogXNU3ejpf3EN1igviAXiwudMVWmc2o+welAhHR+lEi+nsIbjLdL7MLREoZlBiiJL0hlzER9MKqJhTV9NgdXw8+gEN+1hDVbO5fM9D6Yjgy/r1CsgPcUi5Ufyeh85CwCPPY+L5LgTj6+ejMM6sI3rvi2LAyRxiHsk072TaTORjdhOARt9ES2rOT2QK7k1Y3i9WovL9qzyJI1nfxPdscNbh+hz6ENKPfA6sz0FS7+YDTywTrB9i4ulPVZQgwcUe4o0M1ANtNgeVGUN4P8Qjy9fFcOS0hJCXzMDy3+aGWG7FbG7LWdivVmxgBB+Jht1X+fb2lyAuuEqQuKhE76OA0ytd1aKQ5Vk9FCO9shGLb6VZGOy95C6hP1eaU1+Ci+oM78UDcDtFjXFWSJ3xmtTIcKkCdFZUreuL5558BE+SE6l9iwG7aNGZydxi6M+Wole3dwqOQXHmEkpTPu7+4VuCca3G2hkG+8aSenOxdLOd3XvbasQQEYGu9Mk1+ghokzmf1ie/VZmCUJUSyDRS8emyBrlTfZfyAdW06ruuSUmVfFSH2rlhbJ9Ut2luALeZCPi8Xubn68CYjZRbTdqQrSi3Mar513oTHy+wWNMeXx5WzxQByHG1AJpeh0xo8Dxl3Vz0nZURJPcQgyoJrYiVUpI4uTEMx3LLocdeWvVViaxCiaHcK6kFobnKx9lnwuo15NRnymutCL+gyysOVSX1xYYX9KBXrYZ8aDnP5MoPZW8RNcGkL5mn8veQMjkh3G8+mOr+dn7FjPlg2fIePoCDKLY8w7ikekP8KsksRrwk8n+FxVEsqaMK2xpdXOg4/zVRCUoK5SEXwdGI3BsL8vorqLKvJkUmqRcX2SabgM0+1HutdcpctFlc7yUmslqtqF5LmXz+OdkFoM6h8hCOHqphZG/tM2a/AltouKiH32ufvDOgvShqrkttMfk0eaxm4W5OLYlZtTNRut1cPdDt83naRoW+EPcyEfpXhDuyEUrVcSqqjX3O3zQzl/VGr8S9IHoyKmsJFV/Wo3qJqFtlrRm9nqjasp04kW6GipkMNyrewAqlcKBMksUFAZREVV2hVpkfSYSuwlBlTZsQ4Yb7wRgGTdxG7inXR11NytFaY9rkch6sJCxZpYpMNZpPJ5z7SklC7bFYjNFDcKP2nLYysb6iXHvHN/7ayslQ6K3qgoiLz2c7SozpyElNR9X0Pqu5+lMwwPQRNP1XmzzDVyyKGoOFaCyD5cnJEg+FOle0OAadJHVOLT2efUEBrHNXvzG3kn0ZMAAoebhhyWEthb3TXdoE1HbQeks8ocaDw0bEobRe8oRpQOYfk0q9UQ064xg6PiqM/aeqvt6oEgc+mly2XkUPwDW1dcz7fJc/WE2jYRZZcAtZo6WmayhPVro+CqOjxUAccKAcdU6hSo7UfMrgAnilhtRyt7iCA+DRJmOqgdTvbOyTqeMQsH783kv1L2ozuoYQOKlMvloMWM+YPK49mg8y6nNQGrXu39Dgk9VkBsZRiFk1RKnZ52pgjo4svlTVF6w+gi0S9umGu3FNXoMs1pjUoG8juuMhBkUO1SWTKiVOuPh9xdexsqu/6bKNTqiuX3Vhkzo/Fj18jDwSk4i91jzhL2QOOIecS/fV5vHBnxXaVderZ2ld5qL6lkkEUPRRbaBGYqHde0TSFuJtBwGBGNCkdmQeXU0uKlC7tVrSahreM9PwmHFNa6nnZYYV89I7h66HNPKRAg2PxIEkiakyDwFymmJSxqCem4vgAS89FTMLWe2Ou/hoG2sA6c3jkFu0UlMPyJqc4L4wMYhnlSJqiyk38JRpqb7pTVQ2t/RQKtMMDTDc21qIXar/gh7Av9Y7VlQEt8nLOldTceaQRKqlmLwLK29mmNGOt8wbRlNJHJ0Sw97wUKHMrWzpYk7ZP/2KCb9Lndd35j4ijqnavJTSJ/KwxcNU2VMCzllvj9sSunKQ/fBYE4wAVbtEerk5MPI4w3W8gG8wurUc2phV4AJCtr2bV9gKU3MRoKuo1Da1gUGqX92LkcNTA5ljOerxNvZjjuTEUQm1BGv/a/4tnRV9SfrYM+fkcy0y+kItmMWR2Ecwi77k67cIjMKQvnge0KciaKSiN4Pl9c263JJm8LlP0ujZ5tWa5HZQ4RrNqI+6c5ckwC7SHqINpGAfwLGZZKuJwflEKanqSDREpYMKqbxUDETrUkg+VxzzhcdOW2CXm7WztDEP172xc9UIqZWWWiri02u3xLaal22ukmppsRadMVjppLYkEuX9ZSKMhxlcDWNOrhkFExTI6UBNX1tpM7Fc481GcqyuUNfk2caHUyjEqVUXHC7vm7mzkE8ZYN63qGdRubIL4OF5X0WpJneakOlka1vMRovW0+HSbii2S/qlcvCTXk8Tkja1maXkGbsBLfIkoXPJNBEFQAFJXXmpzhBcFBAh8sIplKaqv/soMEVUZIVuJXLz+WAU0bcbfg+ioFX9xUqF7+BOOeR9t7qlT2+eHNCrVeYNIxF1BweDutab2lf6V094B9mF1Psy87T5CP5g1zoqnJcpREqFJqiBHds1hqLKbKbHcMM+pOWgtC5VfATt7T2BXaBMNSR9z3UiCYHllKrHG49hio+6lajMKffvfFhLoTf9BOoq1kc+Vqk1HxywqXjkvIuYceog2Bm0vsUy6NCDsTca747OScaWijqimMVFv3eqneTbUwmlxtKSf6v9TbnuCwvWEClwPDKpz5oVXPR5Dpxm4KgqPquR6JMIJw9sKkzMY/iRyzrbRRyajYA2K+c6imDM8vHocmtkdDskhxE2iU1gjOqU+eiAUz9iVX+QO3VfXD3Wl5acbU4W54lQxXgeKs2t1KHQRPycPHOkp1FA5D/4PUa+Dqz4bs0MakyLuorZ5+qTS0PMXpF4c9kHuvWZQq3ZhkJ6ILCtz3Ek51wAj46ZEW2Hu2TaXhoowSH7XFyXVs8UI6PQRhbtDsQYIyg21bNzmq1m7zao0hDtNe8nJV1K3hNFHo+B4kVVbHBlluqfjrPTqNWtE89FcJ43zaSmK09vBMi9LBTisuLzQbfCqiilLEk4D8HUq0bmwdQNe7Z1VDw6AJu44FB5MAqlSOfqUwaYB2shl2yj6F0ATt4UEgCJ1l9U+4QswLYD6mMonkwQ5Hc0AdFDTb+Uqu20dNF8Xi2HqyP51mzBpinfdT1D6vAl2AqC7r+sk214WyHTex2aYsbx0xh+3INDkGhICzVZtsyXTI+ZocElqdyUoe8cdEiN22KQWm0hlHuTf3IeAELliE2xYprIN+T8EZUoWYoNP59J2M1y26etAXMiKQVubVgwd2ijnevx+ZGJ1IVF1l4k0e3Vbz/gaUOtutEP/Fybh9T/tmfO3QWHsups6KmqmOpTZnOJAJEaCZW4JfEB1MMbAtlRsaqc0d/y7wFaBFtDyS01nxTbzMRV+O+AjgWCEQOwWdKDY59wC7A0KObAiUn8SzrZCbBV8ip7C0/ky+YE5O/LYc7qY4xioTOe0A9pCpGEnvQEH8DjI2e2SUC97dYmzI7KlbVQOimr+6cDKx6Sfn7T55PPP4nRQGp0bIKN8IyHQPmxVm0kZZ/RBTWcIpnCTv1hfJGTfn4a+z08BF7mG9cMaoV3t3bq3do7thVQ7DJmVRjACsUUexAeK6U8xLB1Ui10GSuu3dPH/o/3GZ93CdVtNjg2vpCKhEzDtXBvGOvzJX35VEaT0vTW6oEmiBptDnlpI5ty/Ls3uGvRV7SnVfrTLY+0fCvF0lxwKE8r6onVBrm6lIH2kVjeP1UXwFaOtw2L2EvLTsrtUgqcSzbJ6KHcDFRQWeOYNCnWzeJyitk6X0AST194zU3KQ+mgwsU0RRSfDmXlh4s2w4PDg4jYV6slK9Hn5tMj9mXsXWAf1b4HZaPbJpdxE/tIlUX0uRnMS2pvhCI5l+TTxttEBspe2C6PFEu9861hvL1RTOorhx8dugKpTbTOYf3bfVohpxlWCtQyT/TYPoz888GyPyfIYh6Sysx8B6Mj0vQ9pFqk+SL7og0LVoLIOd/eVrvVq6+m8rYe572Yxhqp9tu3KlwfNhjDQwUfjOEdbivpQdxS9FXnbtUd7p0c91FtRb7pwMqY4Ri5jmW7LmlolcPbxECCkSqpDC4iww/1EAEzFTWGumwVdW/rWp/BMVqASBCkkIaT7iM7eVwH1W28yYNujKx2bE4XU5KQXmoKbTFbZp//uBICK/r1Tm5uEHmU6B+tjb244FAaoKoR3LuZ597hmykF0AAxZLVeWvOvBhfZrmwlHSMs6gA4ecWm6pGQuNbOPlk2e44ObjgIUeEQRb2Q6iKCqh8V2UW4+6/4aPZfbXc7o7Aw2TryIfi92wOO85Bm86sayaOeFVn5HZm14CP4GveCN35duPhiRxuqkVNVs6qjGbpvcU9z7snpI7JVAqDWGDQbG9kmamt/cl9OtW6s5ExStI0QLrqVbLQJzU8HKxk0ZrfmkEXaDBmwerFTiCVX8sX3E9Q7HBYMuA8BFyxIfHtTFjCfbeuF03haHoDzGoSs09WaY8QFBJ0kXLepsA+6EzVEtwZSF8Ej+4Oo96fbj6bgcm2ZXHC4CFKLrVT/8D2ChAlPl27bx0rzb8dban5MxWxtMhisyRbF61lSfYoBH3rJFtpi/8ou6tcxOUbJo57IRXFjxe8+0tRWFfd1ounVMpXzbtaGt1FK+o//kYCLNGqzonJ9CvOXsCZur6ZIrxmQoJFp1IJILkX81wBKAbKevrDL7C2ix7coiuzLL1BhI9ugUS7Th4gbiMDq16s0Ur1/l0QEb3QQ5XyREeS+6xWf5GyJyuxOtmBzTqOnGNcgXdSgpZYmagYXA7FFJlKqlIk8RjoZtqmnpua/7KuuMcTZsu0FN3e7AAf57XuRPQC7LV9gTNn2IQweEPSylKhGi+pg9lFcNX22Es7RKG3WTlvljkUzsY5PTbe3XTwsZ+6hgufMXZKcsUzCBXBuM1RXw7vZnH8X1HX9dGVa12u8WvZ01gDxbOWoi8DySAwswSwcSrLid5+ejx1lRSoe+rLWaEon1CIhtV77qHtyEWCdWTLrLI31V+5tbVkEOeh5EKKuHFwWy2MmJA4bXC/aBfAeM98pyoAju6uEbmut/ZtDzzVV6TlTsa+w00Vf8R23QFgaCFvGW6wU7C5e2PcjXlpI27CRrY0LaxOp5/58C7Y8VHibyDn8lDpC907O71q1rjtachoeMnovcBGBZ/UW1mCXRyN5e0hbce4ZHUCthjzG0/ksBKyVi2ZyJduk6dLnWn8kaBsIJYVhnqKPCFTAwXFXjd7p1/ZEbD20qED7Prt0xsn7Rk0AiqYs0EqdvKcfXpkLVVjCT7flK7qo8ArLOTy19X6udSfhOpN6DxbqNUHkgaMD8+BKqxMbhJiUe13uOXnFl3oOrB/f/GOPRk7xEbAHhlINtBTKuzQDna4+cc15xGK804G1f2zdSHV2Ow8wx6jnkPoYguDyDSjXpibGWhA/pcuNSgUg19rAxLXBZMq1oGZR9cZjWXKRM/ps4vdq/hqkqZpy9RLt8tABF1lQDHM9/keXe0END+q3d0o8zvBwUOEND48kuMl7tqQhFZtc7ALAT97rY8OqjWf1gIALHosssWMPwbNuseKtYPQu+oEm8yUKVNOMhn9UJkGa0tS6nomkLRwzqHdSs6DeZ6GlLtCj5G5nYzSwbXajUQ7uorg1snhdSvp+03i8iMlCbJe2jYpycYMsJ6u7o0EM9/Qt/onz1iTmYMvWJ/yd2vd3yF8POaDT7YOUb++DeFhZdafciF1wKDNBTU2RksSnDHBsVApWUt7c8x+9SckSV5SzCSuPSv0wIw7XUpbUtCsx2zwZF83JgZLKVuIaZ6jeJYLp/ahh1DwnNvOhVp/P91WcAhWeNsep58qqtdwnj02EUo82DzpPpOJCk8vSmVSvFMAjjATVDVT6hKf2KVxygvo3s6XalDsXEa7l16ZJcU0WV/IE5rVxIaD6W7IlXJHIZyNkE6R+s1pK3weghiyhNmp222CdeMKn+c1w/c4pARWZq7Gvl88t3Xc58jaZ0cw0EKospFZHT3InKkxMxkYd3+p+PGz62JygpdUfgqbaRuYlD+OA2tuuv8SLwUSoxilKe8Wbh2qL0q6K3ZicjyWhhwAPqHs9NfWKVJ9amtZDKocYCyKtX0JL0ZYRzlhrj+y4XiyI2dSOVXk9hkO71EJObFCnYy2A8BCcP4zLpjXIWmc6Q7ZFmeQtWneBEOnFWhHLrV04j4tye6jgUW7v8C29/j6iikqrxy004t7TkYkQPiuH3GrryUdxq6oGqFj00mq0+eI+MnBfcLEt6JETuyiOM86HQb3tOaxQdDaBvZiE9G8PVg9GgUrNsxva5i8f28lQlVjFIjA84+Z9mviKZh3ys41kOsFsYlbuHvM+7mIrUHQ9q3c+1xS4qJ5agCFaZYj4/LsXVx8l0LtYw7X2nHLw8vXny37ar2jNW/npFrxFFxVe8zqHJ1Uv2eIVcbmbve0SZ9+2GMpS3u/eFS5VaevjOw3h6VFmi8icmMnlGHIah7ik2aYmX8ndXNjfqAJtW1g4qso8lGAJSlGUjeIMBTTjrf5kGxNvXAS3h5TE79usEJp5bwCbEgrkeFebh862t9xFAHRoW98KIV2WlY9qlq/WwUaTesg6IMae2HZb6TRhoh+wmwDqVQKN9nIrtr259ugu5QpTsgcLQOTpFg9FFxV/s1uDnGyDl9uibB0Aw/+2ZF9c/r8ZnumbyqujaqF0aSqMHzJH/fPyg/ZDDLrcrB57GU3Q3scg1MDbFKI0C/96pw93xRB8W+hCfaVPu592RMiHYX08Vitan+phOKjwprFz+MN7Ptz7umOGHXCucSp1i+i7KEEWaC16pO3L8S9wteC3WqaLfbsnzH4WVZZ1eMkuyi2JtmWPEAaYzYC2YJp/W+5+4oMliwjK2Orr4fjMmB4XkVW/N/CqLD0UyLYHVdfW95DmjF0OF4YagEa73e6gQeXs1TKOWSzVM3s+x50RkPKFGqTHYX3c85ARCouDNbXnOzjzkIzbhNxef/NO6IFszoPFYS6yVZ4+k8URUuPGxQWHMzxKieN5O4fjZ+Ta/jbjZu96nmVIbjNV35t/X/MRafGyaQ6UBYklVEUxY/333vx5Y1bNKFGHkErzEa62Lm9zwjKWbj0FvTo93wUFCsHENCbAF3ZPR5YMpjGQQ6TPn+RhWu8JEWnO1gmqXqvPLsjVmOppdCbOvgBA5+taC1VS6hMOxZW4i3JpKcwT1XGSZajf5DrjV+CLkVyDilkrZp/xJbCHXGoNVqFw39sAdQJ3W75CTPU+2XHeKm/bRJqFhXwuQU6blRwaLy7E7NXCJu2mSMsylXvNFuyCxGrV6dlFBebY1m1z96gU8UA8uKNoVIlI03txLxCXNUuZQmljRLGLYKPFwaa89PGA/p1pRSvBfB737g1blWXM9vNgU2HggOLPJySBnPNHykKPH72pvPCS/bd9XxTTL8fXeCufQV/XH0LmMUpcRmU/080GIxk1FxuutD2rDdBsd6V7Pn6SQ1Oe4JLUKnNwQAc52Jw8LuQDeNI5DlaHF5mKe4vguYfWIKqHeWwEnqBsXS0t9ypTXn5dIiXbZL/dIgCCq3noZDW2H3RFXb+pWsJ/YRfxJZBbnmooVa2kPr2m55j2wVZOXtSHd18XPIxgVdIkLm/v0frrjUeo0c8ldGFF9CDOFuaglM/iCx9cRbQt1mmUldouBbadBFeWKYC656RZN1ZPPuci10xEq74ZeUCPMj+lVBxleEtZBolfo1x+d50YBi82CXHUdXhYgG63mkbLxhvn/P2B31iZvXdII9pZa8g92TyyewAiUk0cSu/Gqt4NfTnMEj4WRyAMQhWJS9bXA3RrAtOVxNJplS8WulBPzYGNLg8vHMannvHSOmkUOaS66/VIs3leHhjUoNEaRumCTC9jLWmzlN9e5nZM9H4/kvr/AQQRVK4KZW5kc3RyZWFtCmVuZG9iagoxMyAwIG9iago8PAovVHlwZSAvUGFnZQovUGFyZW50IDEgMCBSCi9NZWRpYUJveCBbMCAwIDU5NS4yOCA4NDEuODldCi9Db250ZW50cyAxMSAwIFIKL1Jlc291cmNlcyAxMiAwIFIKPj4KZW5kb2JqCjEyIDAgb2JqCjw8Ci9Qcm9jU2V0IFsvUERGIC9UZXh0IC9JbWFnZUIgL0ltYWdlQyAvSW1hZ2VJXQovRXh0R1N0YXRlIDw8Ci9HczEgOCAwIFIKPj4KL0ZvbnQgPDwKL0YyIDEwIDAgUgo+Pgo+PgplbmRvYmoKMTEgMCBvYmoKPDwKL0xlbmd0aCA5MTkKL0ZpbHRlciAvRmxhdGVEZWNvZGUKPj4Kc3RyZWFtCnic3ZnPbhtHDMbv+xT7AmZIDmfIAQodgqYBekugW9GDLFtFDw0QGOjzh7O7kiVUnXXR0BYCYy17ZXt+yz/ffBzTiP5xR/7JhMDquP9rePfxicY/noZ3Pz/+/ef+8fPH9+P+acDpR5/2X4bD8HWga7/4frvcp5EQOEnSPGpF0KxkNm79b//CI/G4PQy//YSI9JJrM+Lv4/bX4cN2+PS94bRAqVJuCE6wSyXsi9aQlTODmWgpXQA6+OIJke9DIHzllCmX1IVgjz3lGYYf/NWWe/szQI4snMJQEt9SVQtDTljZ+nAeGRS/PHpYYlJIkIQocx9E/fK0YV1gdpuRqj8CcR7b+62+8masoCWX5Z7F6AGTr2tYS59YwkJGqULximXtE+xaPFg1iUzxcJrkF6V/xo8PMaSaQbwFkLqkpDGrm2sCW+U3yxSjuColzP1MTRmpZ22284yk6xmcfub+1TLI3p/V06N9oSCKi6FbgoIma1J1P6sE6zGGl7GbCGMUIXk/im8+SV6uYQEURUDZTFdU4WGJlcRQWAbTjKmuU5TN6Pu3NMWeMqSX309ZjKEUMlDJRiu6tKhlU82J5rxHg8hKBaqiuKIYcf0mpmBpVbNOdRRgLZFBLVteqaHHOQZNKVOj2c9Uk5pqGF2z3GKQS70+CBzmLid+1vULojq/Uo00nEkg462OUYxuCm5ujOpQTcMCLxUWp53ms68pYe3DpGcDcMcCQoKFJ8E8k6YWpxDz29LIwtxP4/0iEBHm1xUhC1ftEqTdbKOmtC3RKgjYVGX2A0EBavqN2WV8PUD6rF8nVxfjDZgyoDK3ab1HdWWCOvmmmJrnJqU4a32P7CGWoiisa5PnKD0+l9XJtcdxJdLmprpYQcNT4gKZ61qfnZvaVirHrW56PZrdOLuUqoC3XF3Ro5NdkoV4txBeOzIIMnbi8TTGRP14Hm1mhLVkyGLWBqk1gtgzH4eA1DY6eXFt/ZdDn1hrhT6j2Cue5X1f/KIGfFsH7HcExYEanI+w9L8O2MNha3a9mSZUL9y2o/pXR1Y8Hbun17gCitwfjiaBqOB7XcUrz8bHeebcXEXYvASUc009lsApmJpcuxv3N/59/el4PMjmZgVSkcq9519E8VIAN6NCs+hUJ59brpyqlDNftws4A2Iw/EGbxHdGQCnC5e2bRNgALeWU36ZJxG9mLMn0bZpEMvuwxdjr0fbPvtOp0MUZ3gXON4+WopsKZW5kc3RyZWFtCmVuZG9iagoxNSAwIG9iagoocGRmbWFrZSkKZW5kb2JqCjE2IDAgb2JqCihwZGZtYWtlKQplbmRvYmoKMTcgMCBvYmoKKEQ6MjAyMzA4MTkwNTE2MjFaKQplbmRvYmoKMTQgMCBvYmoKPDwKL1Byb2R1Y2VyIDE1IDAgUgovQ3JlYXRvciAxNiAwIFIKL0NyZWF0aW9uRGF0ZSAxNyAwIFIKPj4KZW5kb2JqCjE5IDAgb2JqCjw8Ci9UeXBlIC9Gb250RGVzY3JpcHRvcgovRm9udE5hbWUgL0JaWlpaWitSb2JvdG8tTWVkaXVtCi9GbGFncyA0Ci9Gb250QkJveCBbLTczMS40NDUzMTIgLTI3MC45OTYwOTQgMTE3Mi4zNjMyODEgMTA1Ni4xNTIzNDRdCi9JdGFsaWNBbmdsZSAwCi9Bc2NlbnQgOTI3LjczNDM3NQovRGVzY2VudCAtMjQ0LjE0MDYyNQovQ2FwSGVpZ2h0IDcxMC45Mzc1Ci9YSGVpZ2h0IDUyOC4zMjAzMTMKL1N0ZW1WIDAKL0ZvbnRGaWxlMiAxOCAwIFIKPj4KZW5kb2JqCjIwIDAgb2JqCjw8Ci9UeXBlIC9Gb250Ci9TdWJ0eXBlIC9DSURGb250VHlwZTIKL0Jhc2VGb250IC9CWlpaWlorUm9ib3RvLU1lZGl1bQovQ0lEU3lzdGVtSW5mbyA8PAovUmVnaXN0cnkgKEFkb2JlKQovT3JkZXJpbmcgKElkZW50aXR5KQovU3VwcGxlbWVudCAwCj4+Ci9Gb250RGVzY3JpcHRvciAxOSAwIFIKL1cgWzAgWzkwOCA2NTIuODMyMDMxIDY4OC45NjQ4NDQgNzA5LjQ3MjY1NiA2MDkuMzc1IDYyOS4zOTQ1MzEgNjYzLjA4NTkzOCAyNDguNTM1MTU2IDY1Mi44MzIwMzEgNTY0Ljk0MTQwNiA2MDUuNDY4NzUgNjQ1LjUwNzgxMyA0NDcuNzUzOTA2IDM5MC4xMzY3MTldXQovQ0lEVG9HSURNYXAgL0lkZW50aXR5Cj4+CmVuZG9iagoyMSAwIG9iago8PAovTGVuZ3RoIDI1NwovRmlsdGVyIC9GbGF0ZURlY29kZQo+PgpzdHJlYW0KeJxdUT1vxCAM3fkVHq/DiUuadIqQTtclQz/UtFPVgYCJkBpAhAz59+UjvatqCZ7s52dsQy/9Y290APrqrRgwgNJGelzs6gXCiJM2pKpBahF2L99i5o7QKB62JeDcG2Wh6wgAfYv0EvwGh7O0I96l2IuX6LWZ4PBxGXJkWJ37xhlNgBNhDCSqWO6Ju2c+I9AsPfYy8jpsx6i6ZbxvDqHOflVaElbi4rhAz82EpDtFY52Kxgga+Y/eRaP6mw0JJIPPm9vcF1AFMEPbFKhLsMpQ74LCNW1JKfL2oUCpUiv2lVr6fTx1lzZ5nVys3seh87rztGlObfD6I866pMrnB+TchhwKZW5kc3RyZWFtCmVuZG9iago5IDAgb2JqCjw8Ci9UeXBlIC9Gb250Ci9TdWJ0eXBlIC9UeXBlMAovQmFzZUZvbnQgL0JaWlpaWitSb2JvdG8tTWVkaXVtCi9FbmNvZGluZyAvSWRlbnRpdHktSAovRGVzY2VuZGFudEZvbnRzIFsyMCAwIFJdCi9Ub1VuaWNvZGUgMjEgMCBSCj4+CmVuZG9iagoyMyAwIG9iago8PAovVHlwZSAvRm9udERlc2NyaXB0b3IKL0ZvbnROYW1lIC9DWlpaWlorUm9ib3RvLVJlZ3VsYXIKL0ZsYWdzIDQKL0ZvbnRCQm94IFstNzM3LjMwNDY4NyAtMjcwLjk5NjA5NCAxMTQ4LjkyNTc4MSAxMDU2LjE1MjM0NF0KL0l0YWxpY0FuZ2xlIDAKL0FzY2VudCA5MjcuNzM0Mzc1Ci9EZXNjZW50IC0yNDQuMTQwNjI1Ci9DYXBIZWlnaHQgNzEwLjkzNzUKL1hIZWlnaHQgNTI4LjMyMDMxMwovU3RlbVYgMAovRm9udEZpbGUyIDIyIDAgUgo+PgplbmRvYmoKMjQgMCBvYmoKPDwKL1R5cGUgL0ZvbnQKL1N1YnR5cGUgL0NJREZvbnRUeXBlMgovQmFzZUZvbnQgL0NaWlpaWitSb2JvdG8tUmVndWxhcgovQ0lEU3lzdGVtSW5mbyA8PAovUmVnaXN0cnkgKEFkb2JlKQovT3JkZXJpbmcgKElkZW50aXR5KQovU3VwcGxlbWVudCAwCj4+Ci9Gb250RGVzY3JpcHRvciAyMyAwIFIKL1cgWzAgWzkwOCAyNDguMDQ2ODc1IDE3NC44MDQ2ODggNTY4LjM1OTM3NSA1MTYuMTEzMjgxIDMyNy4xNDg0MzggNTMwLjI3MzQzOCA1MjMuNDM3NSA1NzAuMzEyNSA1NTIuMjQ2MDk0IDMzOC44NjcxODggNTQzLjk0NTMxMyA1NjEuNTIzNDM4IDI0My4xNjQwNjMgNjE2LjIxMDkzOCA2NTYuMjUgMTk2Ljc3NzM0NCA1NjMuOTY0ODQ0IDg3Ni45NTMxMjUgMjQzLjE2NDA2MyAzMjAuMzEyNSA2MzAuODU5Mzc1IDQ4NC4zNzUgNDczLjE0NDUzMSA2NTAuODc4OTA2IDI2My42NzE4NzUgNTYyLjAxMTcxOSA2ODcuOTg4MjgxIDYyMy4wNDY4NzUgNTUxLjc1NzgxMyA1OTYuNjc5Njg4IDUzOC41NzQyMTkgNzEzLjM3ODkwNiA2NTIuMzQzNzUgMjQyLjE4NzUgNTYxLjUyMzQzOCAzNDcuNjU2MjUgNTUwLjc4MTI1IDI0Ny41NTg1OTQgNTUxLjI2OTUzMSA1NjIuMDExNzE5IDU1Mi43MzQzNzUgNzEzLjM3ODkwNiA2MDAuNTg1OTM4IDY0OC40Mzc1IDI3MS45NzI2NTYgNjg3Ljk4ODI4MSA1NDMuOTQ1MzEzIDU2Mi4wMTE3MTkgNTkzLjc1IDI3Ni4zNjcxODggNDk2LjA5Mzc1IDU2OC4zNTkzNzUgMjM5LjI1NzgxMyA1NjEuNTIzNDM4IDU3MC4zMTI1IDU1Mi4yNDYwOTQgNDk2LjA5Mzc1IDU1NC4xOTkyMTkgNTYyLjAxMTcxOSA3MzIuNDIxODc1IDU1MS4yNjk1MzEgNTMwLjI3MzQzOCA1NjIuMDExNzE5IDg3My4wNDY4NzUgNTk5LjEyMTA5NCA1NjIuMDExNzE5IDQ1MS4xNzE4NzVdXQovQ0lEVG9HSURNYXAgL0lkZW50aXR5Cj4+CmVuZG9iagoyNSAwIG9iago8PAovTGVuZ3RoIDM3OAovRmlsdGVyIC9GbGF0ZURlY29kZQo+PgpzdHJlYW0KeJxdU8tugzAQvPMVPqaHiARs00gIqUovHPpQaU9VDwSvI6RiLEMO/H2Nx02qIsFod2d3BrOkx/qxNv3M0lc3dg3NTPdGOZrGi+uInejcm2SfMdV3c4zCsxtam6S+uVmmmYba6JGVZcJY+ubL0+wWtnlQ44nu1tyLU+R6c2abj2MTMs3F2m8ayMxsl1QVU6T9uKfWPrcDsTS0bmvl6/28bH3XjfG+WGJZiPew1I2KJtt25FpzpqTc+asqtb+qhIz6V45NJ/2XzTzwvGKftzCLUKAoAhQ5gAeQSEokpQYQKBmiPSBGXQCBiGNKhqSMMxXggBqYAl4KCThc/a4U6OUQ4jDBo0KLdozmEOJo4GjIQSmgIKEg7wMQvBR4zTzOBIWDIuBFgMIRKTijqIBIRLtxZpSNx4NI4qw1mBq14j46Y9dTyaGWATSaKdbiu0JGoJbDs9DV17oRv99+XY51ka+L112c8zsXtj0s27pmvaHrD2FHu3aF+wf+b9XgCmVuZHN0cmVhbQplbmRvYmoKMTAgMCBvYmoKPDwKL1R5cGUgL0ZvbnQKL1N1YnR5cGUgL1R5cGUwCi9CYXNlRm9udCAvQ1paWlpaK1JvYm90by1SZWd1bGFyCi9FbmNvZGluZyAvSWRlbnRpdHktSAovRGVzY2VuZGFudEZvbnRzIFsyNCAwIFJdCi9Ub1VuaWNvZGUgMjUgMCBSCj4+CmVuZG9iago0IDAgb2JqCjw8Cj4+CmVuZG9iagozIDAgb2JqCjw8Ci9UeXBlIC9DYXRhbG9nCi9QYWdlcyAxIDAgUgovTmFtZXMgMiAwIFIKPj4KZW5kb2JqCjEgMCBvYmoKPDwKL1R5cGUgL1BhZ2VzCi9Db3VudCAyCi9LaWRzIFs3IDAgUiAxMyAwIFJdCj4+CmVuZG9iagoyIDAgb2JqCjw8Ci9EZXN0cyA8PAogIC9OYW1lcyBbCl0KPj4KPj4KZW5kb2JqCjE4IDAgb2JqCjw8Ci9MZW5ndGggNDIxOAovRmlsdGVyIC9GbGF0ZURlY29kZQo+PgpzdHJlYW0KeJyNNwlwFFd2/3f3nBpJI6ELRtLvoZkBMwjdQhJXgw6QxDG6YFoSYkajA2xOIYS4LCGWw20bewHvGtdS66ViKg7ldQ/YzmBje+2whZ2Nk6rdpGorydpbSSUVL47tqhSuNbKm8/7vHiFYZysz/bv/O/777/7dI8MHB5ADTSAeuXcMRPqR8fsJjKodgDDhX8NYsGtvNAl/A6Nwd2RsnwHiLLiJ0dER0YQr4JbYNzxg0rkyGH8/tOvwoAFb6CjbsXtkzICdQEfVg/uGdpvw4wiln0YYpjxe//m78vj29BX30Fw7o97+OmMpfX5mfX/3ff/0Pzki9gMAOhBnbI6QbVfCBYg99/2JVY4IkzP7lwajDI2iD9F/YJCPJ+D/Hv6S28gd5E5xlxh/GnoVZQOPDaS6UTF6CSz4z/SD4CdsRSjboqEsOoRaBLbrXyRHIqzfA3w2zO+ClHfRL9Bl+L+Nfgz/hQw6jW6ha4B5Cf0G3UCX8O/Rjxj0Kk5Bk+jn6GX0DHoB3YT9c9EFwB9FT6OfoU8Z/jJ6y5TyFyDnCsh5C70PqyfROeC8gq6DzB+iS+g1kPwe/hhPM9nr0IuwwpB/Cf0UJGvoBDoFci/C/E3gyEVBFEVj6Dg6Cdjngf8KaPKP6FPsh/2fAj0uo1fQG8KzyC3rT1Yc7zy2SidHl+vkyEqdHF4uk7EVOjm0YiUZrbSRg7U6GakdIgdqNpPhGp3sr9LJvupPyN5qnexZ1kt2L/uE7FqmkyeWFZHHl+WRnRU62VGmk6GyT8hguU4GSnXSX6KTaMk10lcyRCJLdRJeOkG2F+ukt/gC2Vakk54lOukO6KRr8SdEWayT0OJUsvUxnWxZpJPOhQtIx8Ii0u7rJW0+nbT6rpGgXyeb/RNk0wKdbJQCZIN0jbRIOmmWtpAmgNfP18k6USeN4jBp8Oqk3jtM6ohO1hZeIGsKdSIX6GR1vk5WLr8g/4GsWF5BaivTSE3VMKmu2kyWVc0nVZUXSHmZTEpLhknx0mYSWCyThXMF4vctIr5yz9yeBfMyiWSZN7dn/lydeMWVRKzOy+kheUWkMFcnBTk6yc+xEU/53PzuvIqc/O55dJZLZ9lzV+Vc7ZpTmtmZUeruzFTcSmqFq9NSIXS6FEEhwnaBSxfGha8EPr03rTOlwtlpq7B24lLUmaY4FasybsXF1s3WvVZ+tXW7ddzKI6UY4WK0F32FeEeFvZOv4DrtCqcQbjvHpXPj3Fccz8uyBcfx81pHoCVu09taNEewW8NnNV87vcutXZr1rIY6u7pDMYzPKaeefRYVrG3Rnm8PXecRTJUYx9W1hmICf045MIICKBAI0OeBkYMUoKCBoDPjjmf9KQLTi5IwYzaQfzpNzv6EZEDs9zBP8peHrAh6Hr8IapaHWk9B6WgOVANak+2tLM+QMrww5sAcYwln4HLMO6ZHPVXc7arc6VFOnX69lmtlN4tWVXU/aNHYOF1VZem5/4xlxBjQTwb1L4S7lttQu9myc262mx9egCyOYRT4u3K4SkrXlKdx0vylXGVlxSquvCwnJ1daCog0Ljs7qxAQVVX81/ddZ7/Rzvz2pdb2n/zLUz//+lT6fWfd5M4tE1sCC1ufDD1xqgH/83OfTURuJC4fvpx4Mzzxb+d7T6+Tj705cnTPjYnG+pPQwNCA/oWlAPTIBqfOkR0LrfkZ/LCVKhIoy6B6ZGdxVqs03++nqmRWVVFdMm2VFQ9ps4qzFGz56adnTv/uihL62e9On/n05a1Txd0/aG+f7C4p2TbZ3jHZVcyj4CuJ+/FIJI6trwRfwZabkcjNxNS9tiPvjK9ZM/7OkbYjt06sWXPiFu3YF+E8yIUYOFCunMLbLQ4bN8xZ7KBXWaAss6YGNMuAAEgZ5TjDkjs1fWBqinuOeluYM/XfFm3qrpAN1hUhJLxhRhL8jHjeCnKwnZln2EdDCuHk7n7LfTh12IjXRx/BWtBA+AzW5qECJMmZnnkO3uVKSUH5c/PswzmIM1QBXYrLM3NBn3YveCY7y2q12bwLvRCgygq/X4J08WIfzr7I8Vf/cDx4fmBDopTD3V1jK5cf6U38cYpfnfgrbMPdFq3/b57bfXU/8d2R9zZu2L9yKo87h6efTAXdM8AXq0ETAbyRih6TswSbzZmaakUpLhdn57lhC2c6JgOUqakpzyg3bMNeSFC8EAa18FeJjYlvuQV/ibsSG+a8yvkT//7dfwlfTmUyr3354f0gl3/nDjIt/zXsNw8VIo+cymFckJaeXsgNF9jNvKD/ktKIdxmzkyWDt9JbVkjzIY2jYeGWJz7mcOWZv95WOfRCJPE2bvzh16/39mr/k3hv6s7ov764efStY/JHkbcSlzdCbkYMv4OFdO+Ns2qvQE5LcTqt6WkQN56zMjup26mlJaUDYNcc2I3aR4ew8bupdVN8x3SYR9Pozp07wudU7vTLt29zYYgqRi1Qd+cg32sQkdOd/vSq0tKAYzgvKyudp6KLy+jIYPkFVi1cyifrL1ui4ZxvtdKMzy3kqaGsQMuT9XjeU390+47XJ9e3PP3egSt3x79debRXGa31bxoNHn5jbEXzU+8f3Pmrq31TpaGDdaFDK/ChosbaZQXi5p1PdSnnn1g+9rdH1u+Vq3pqH6urKctdsHXP06GeC0PLqg+8NrKuf3VhWRdEhmaCx8wEqAtktWMH+MX+UF1A1CWM50iYO4PHcfb0N+8k/gEfq7g1/UfsFK5Sf0x1Jb4BKRhxej1/nr5TIXuM4xF1aQTcyJ//bt+tW0DH+knuHouG4zriMCpeTeWD5HvTH7/LVVu0b39jLeKfQf2WGjRoOYkGLK+hi8LvUZHFgS5aNqEMeN9AQLsonILxW9RiWYwy+BcQxxOE5eZLL/74R2dOn/rByckTE+NPHj929MjhsUOjB0cODO/ft3fP7l1PPL5zx9DgQH+0LxLe3rutp7tLCW3d0tnR3hrcvGnjhpbmpvXrGhcRt9OxBMdSnHVS3YCzaAmKOVNgmlK0BGvWOs3GkNrmgAhHVMjb0hZqqPd4vYpH8mqyJvga6Ij0q9EkQQERsArWgoiWdqmltSskNqhhRgRMx0OQQa+eoZkzjavrCGmNAYBmwesYPAOuf4TclCRLooaCqtofQ7wP8LInhtnEUve0ApYoktYXkLxSaAB4Y3bk8naE62DmSs6wuA4kinE36oMR3SrFsTnrCmlieFBZD9yI82nsao+jSmnMmIc1MSqKmtUn9QVDqlfDYcljwm0h8BiOeFSv5BUVJa5/kE+5JS/I4tDamITPtsZkfLa9KwRbaeLZjtB1DnN1YTj4FwAtFBeRJjMsR7EUSQGRAqgFQ2Suc3bG74nLSJtgVIEhGBwFKxjOYLopQ4ZG45yBcxsb+elGQOGAIhgUOcktAM5u4CYM7kUmtx0obkq5SbNcY0TjB16CyMhOi2yXHbKLS+UgFhR1HTBvw3eBA6MbLpyKPTGQ2cbQcTwRc8ieOJPUZnJOACfFTczgQHPKNksQ7GcY3vnAgs6u0A0XAvnsDhxr6a9oSUOM2xSQHqR1awii1xDDmwJhSG0K8r4GEdJak9tDlDfsgZyH7K4vWkKzSwxJAx5JiWVlqfsaQIwUi1j94YBqJBlNLcldC4nJ+5qiUmOYckChwNUEqOgWMaz1hQMwFd2NaiPNgwjlRjnQR3wxLPjwKrQKPGV1aU5pYK2WIq2doaxGqw2KlVJs0loN5xh+bpAaxLydalTqg5yTg6Ehz6ASAdmaLEU0QVrriQloLVRIHgYjGmJoUwCsaYGs2xwIdkNZUvNFVa0XY7Lgj0QjFK73QqWrJkmqr1dmrWgQVU2ORMPA0aAwZqg9QDZIEbEf/Armgq/aJfpy20XXdHSFVFe/1C+BT2VZjYDZHjGqeFQlynwM60E1VLTE8qAfme2Io1Xuiw7CDQqhLyz1GQhaj4/ihh5FDALXbJzUTLdjT8yearPU0A8cdET6NR5yzCv2K0aSoCDrFP8nE57FJEJMmXDVvTwJYRMCAC5VG3oY3DEDNtIRBq8tNXJFE/w010Je7XGPtksJzLBEtIk+URXdUq1Eb2zxOjrCmgUmE9EIbUdWmnuAaAaEGOqD7AWBjWE1mXGwTPDP7KTtCTwkEpoo7oCtOR81R5sIimFFDIcBC/Xi9YiaBZ7iYIQmF220QcOeIHR7eETUdliLaMl4NBv0/MHIgOSF/qzRMjW8T3UUQDvUHtKQR1UlVcOgoq8RmEG8X7P6m+gDrn0BKTIAQaT7iZEBtrYR1GXeodI8DZJXARbOx3wJjoP+0EdvURWyUdsG1WbxZaiZqlijQp/aBi1W8Ee3hOEgEN1io8hCHYFMpk5oopACggxGh48ywnp2+bXdgdg2m+8Bhl17AwaznUkFzdpCWjDJYmMXTPYHNC63GojUeNwG54nAAkWdZ/E1gXtlyCoPXS1qXEfIDA9b30SXepIBM5YBhjVaehB6k/qmGPoam1rZ5WKXw6fZfRBoTQAdDLKNmvMgCWAOShtreKauYQDMYSvRpDBDwiYg+AaYTcYBKNKGCa8GEYkOT1z/RRBO4LBEh6LQ7e1sI7qCiVYNwdRdVkr8PleYOxlXCr2amAmz0U522ZjOlGaYZHnY8ab3QCvTc17zR3OGWnnGrEqz7gY82g4l0G+sspodXISOCp072sreL7qhGiSvDfoYmA9VJWrtATg2mG1nDK82G92BZiVulFAj5JA5QTlIQ9J6TG8ISktar3EAzsyk6xzCdqmaPhxSdYzDNuj2tBm5U13Q6NVouN84msHLqNqzgr4MWVmgHSy2o7Q1dYQsHkFhKePXDgXMLDbuo4EZ+iFak7akJ+2Ups4QLUzcISM3/OZ9NGD/3lWq/f+3md2MpuZgNNqN/PY/vxVvBKjZCFczZ0huNvpEM61pVaWtLbYtjVaoy58B+ExQrQaUrDG1BN8cA1WCdGs7wzAQys1G1THC5ksBght4PzBSOwWIbtDmA4/BBVdc15neBrfhBNDb6TPy3CSbq43sPBRQYNZIRxhYGukwKynFrFLXI13fFG/E1PEwUZoRRg96aUYihWLYBW+9gscCO/pFN7irlvnTD6oCrNbGsM1vMlgoA+erVdWUZP+n7f8mQjJir5NIUR9FaMchHhDr1O+n2B/FpjK0GeXUmSdFmuXgrNNS6uj7Cz2bHDQBlkJ8j//S7DnsdWKWYxiKluJsbB71vS3ZEvYGkmuTfhtkJW2ufQTbEToOWOqpX9KTRMPwtPi9dHio69huNMf3BsxX2+M0upNM3GRAFHfCe1YdhrctOCh30qNKpNx2P2tyKrzw7IxEWB9iHy558C7VRt+H4Z1fcot4BVphfP5I5pcFnAGCL7TCU6PAl0Rc/zxfMVoVB4c8jA5VFN0ZQFLFTPi00E4x95o0ieHgFLf6TS5qwSkoToOPau/i1JZ2cAL9BnNWe5z0uy75SfVi4M+RRboeulQc7ZDGvNQXcdQrHYbXhTpJE8UeaIpw1MfRxnxFVeFIVSX6/bQlZNwpEcdRST59P6DvMjP8BfnwdTYb4cqniReJ69fy6afSg31PzOx7CPalMzW5cRwNfe+2NOVwt5F4cDFb4ghOY8lQRPCbe6s9ahd8IAKxkG5v6kPhtHyFSQGFLlCF/hdeZiTeCmVuZHN0cmVhbQplbmRvYmoKMjIgMCBvYmoKPDwKL0xlbmd0aCA4NjQyCi9GaWx0ZXIgL0ZsYXRlRGVjb2RlCj4+CnN0cmVhbQp4nI16CXhTx7XwzF20e9+R7StxsQwIW9iyvAKWN3kHr2AZL5KNN/CGMDZrMBCDI3ZIWBJMlpK2Cc2rTALYJKHQpDQ0pdv/XtOmSduvf1//1zTd3nvt/wqW9J+598qYJO1f+S4zZ86cOXPmrBdGXNu7kBKNIxqF9nY5NyHxdxHuzF4ASP0fwb2kf6gz0P8r3CcHnDuGxS4+BA9d5+iITup/GR6+YVeXNE5dhvt7Pf07u8U+60IoPrV3YGSH2Ne/AHPiu4d7BsT+4rcQCjmEMDRpXPY/S9b3tIes+gvSKoTRd/8Ulkrev5B9Y/DBIu+/KdMU26CrRJS4OELyfp8GABUPFvkqlGkCnYW/UrjT4c+GRtF95MUV+CT+MRVKFVNfo/x0BN1En6U9DM20MxPMZeYDxsvmsHvZ8+w065W1yiZlX5a9K/s/8kT5cvkT8tfk/y7/v4pUxYDirOKW4lfKUOUSZZayQjmtClXpVdWqF1UfqgvVjeoe9Rn1dzQxmvOaK5pbmt8GxQeVB30p6PWgbwf9LDhG4LAUvYKigCM57CMUmdCzILPfhGyHk8EyhKJYD4okN5OLIhHyfxq4fQ7/XwAeBe3fAZW30W00BX830Tn4SxZ6h9Bb6ApAnkX/C72OLuBforNC7xWsRgfQv6AX0FH0DJqF9WPQGYDvRkfQi+jnAnwKXZeoXAY6LwGd6+gbMPsAOg6YL6GrQPMUuoBeA8q38D3sFWiXovMwQ6R/AT0PlD1oP5oAuk9D+xpgxKAa1Il2oL3oIEBPAv5LwMm/op9jA6z/FPAxhV5GbzDHUKjV/0TG3sY9a/zc7jw/t2u1n9uZZ+V2rPJzY6tWc6MWObc918+N5PZw23LWca4cP7c1088NZ9/nhrL93GBWGzeQdZ/rz/JzW7JSuM1ZsVxfhp/rTfdzPen3uW6zn+tK83ObVvq5zpVXuI6VPZwz1c85Use5dpOfazOd4VpT/FzLCj+30ejnmpff5+zL/VzT8iBuwzI/t36pn2tMXsI1JKdw9UltXF2Sn6tNusLVGPzcOsM4t3aJn6vmjVwVf4Wr5P1cBb+eK4d+2WI/V6rzczadiyvR+7livYsr4vxcYeIZriDRz1kT/Fx+vJ9bnXfG+gm3Ki+Dy7UEczmZLi47cx2XlbmYy7Sc4czpVi5tpYszpVZwxuVWLjmO4QxJS7kkszauZcmicI5nF8W1LI7zc3rdak6XHRvdwsWmcIkxfi4h2s/FR8s5rTkufmNsRnT8xkWkFUNaUXFror/cHJEW3hiWFtoYbg+1B2VoGtkMplFjZ+wcWAYVwuxj/sjQIW3BjeoMVaM8Q9aI01BjsF1ll9n3ybBJtk42JKPzZe2yfTIa2U0Im9AQ+iOilRmKRjqDalTYKTtHtVNUCLWP+iNF01Yri2fwSU+DsXJG7q+r9ChrNnrwpCepnjyttc0e2aQHNTZvbJrG+Lh94tgxlFBY6TlZ33SVRtC0T1NUUW3TNEMft28bQUZkNBrJe9vIdtIhXRFAWuITL/gjAEwuMoQFZBH4+Wag9bkhsSf8HscJ/GKRDIGXpZeCzdJg62oUgiLAGlBBlN5iDuPD9HBHQBtjHodhM6aV3lFtJvVuZox3lHJ7v55L1QoP1pOZ+aCG9Qj3ocxMtuXBUXZEvMGf9DKLkQ/8BosU0zSLTHdXptVH0XyExRe1H/zJoO8kbt+HGLBGxNgW8JJgDVarVLKQYDnloimZwoWM6elwheWYzCvTuoCxCGAQEwbhZmxz3uQ7dJa3k/qbVz41NcVGEH68x6emKNelS8BHu/9T+i1mLbKgGKtai4LTl6ldMcFyQtYIRHNWphVkGAzJqbQlYw1lTo+OjuKhzy+WyaIiE6mYRCoqMpjiFxsMFnMijGdm0jS/ZUvzqa7MnL6nNx6Y6Zi1dJVXtxujMjuqJr7WkDd0of3E3e6bTM1ITlVPJuaWluRERWRUbCqyuprSWy60pjRmm8qWJpqSF4clNuzaUDraaOp+qbnKnrTUBn5X6f+U2sAWgDSiUIRVqQpTuxiKlhFuTcZ04JXs3xwWGR0NrGTFyGQCZ1Sd98bd2cWZXIw5CEeXphe7ipjc48ex/OH7WdnhSvqcPChzXz+JTK0gjf8CaRgRZw3ticCyiPBwFKeWu5YgdUAkJnN768q0ksWplEWUCcgAltVbUkEOwdCOFASRFRNMUWu33jhoW3vo1Y0jr/RnzP2EGmLMg+35m6uWG+vHqjomzcN8/1Rk9dHbruVPfv9kRc2JO676c8Flk02W3rMdy6sPd+fWFNktjlUSZ78HzpJRnFWTEBcXKXcxDFIKXJG9m2D3XSD+LDM5jnneoqNj+AV8UWsKh8tYDzt2e9uua2N5eWPXdu27NQCAgqGKxm1FCfFF257MbF/teLlr/dl3BpYPvHN2fc/0cFF/QdHWp0qXl7qHiyDooRb/p4wFeIkCOYXeiIdDSJZJGgNa/EgokSIrWaJE1hCeRF5aisevb3Xd2F9cvP+ay3V9f/GsoXqkumpbVXJy9TZ4VxuosJjt956pr3/m3vaY7e+RxntHY2pPDObnD56ojak5MWS1Dp0gvBwDW/0l8MIgLUgmKJyKUYM+wIlRKhex8DBzGNhFAdiEmU5eQwuMQUfQ4WAK22a/vrgaW0de7KgZ37jyZrrDVrK1NoWun3uNyfVp6KG3j1Yb257Z4s2jvt3YY8rtPiitSZ0X1owma8qUShaOA5aV1gRrDKyZJBcXksvF44AF38AbcMyyRdaO4mRZRnLdvqbIDPrk3DCTK/saSy8t68xL7PjaRCXJlgbgzD+BdbQoFy2zRhlXJCYn5uaGJKepXbFxKpeSDZFL5m9MDwe9DAsn9toVFjBQPmCyYBAxUbzBEBEjaIJoHkRDacE+CBqtNndX2vryZldtfb5j9FpPRMSd4FAd9ea6PQ0rUluLGw9U0+vka3qONQ2+vLF4/I2hWSrF2p6xcm1Krqs1q+bFnT5F5q4VobotFHsgLr0y3dyQVtabZl/e3bp6/anmDRP2VLDZo6A3evB5DFoE+VOcNVgfLXcZ1WDDIDckik5QIXOYnMcB9Um2iMcmD2iPPEpUp6M3Q1+ln8nuv9jV89zmfI0mf/Oz3d2XtmTfTCzsX2frKUtRh5bv3li5pUgnQw9+9CPKEDV67+m60kO3xlp23Dpcuu70+6eiak8M5K+s7cn6s21/3er+48QHQG6N1wOXNNJco5F0puJx4vU3gRRECKIFxDN/BzxzLEpAvDVcu0hJazRqNYqPi1W4ohElGoRwMOExcC71enIUkTKZXK5P1oP8LeScIJzocRaOegX/6vL/Hqs915fpy6Pw+l63rfDYkO8Xd+h636V7uIf1bHrn+KaXt8VHTZXvqWx4ouTBH6insXdME+Dk28DJIpSItNYgCuOE4JCQRMqVQMID+CyzaAVOfZawriBI8FgBI8WwNcrs+wGFUy/+oG/VyFf6fTO47MSnV1paXvsv3/N3pg7+/nn73ncO2y61v+69tOGS92q7GNdAWgm+j7EFfYRUEMcYhEz3SRCKlMmTibljS0t9n25FzEfPbHy/uHzFRmfmeSJXEnP+vEAPgvQME60GTZC7sKAG6ZI/A7Z5HPAnMVFEXefdCeivJZUm+kBn3XzVG7t665Sz+8KWNRp1/pZne9qntq6+qbf1V7aMlUVqUkp7bFUDNv2P2NQHiAqL2vP+6XWlh2/taBm7dai07ul7R6Jqj/evXjte+eesntqV+QMnCJdHEJLtlDxLOtJbw5aFU6mLF3/OvwjC/Qc+Jkn+ebdTctMTvx5nD17urxpvy5jN6bXVDRYmUG/vwTkDL/RsONy68mZOT+nqNque7pybeuSKWk52e03Ue43dxBUlGOyXxytT25/u9uZQ9zZ2LVte3gbaQJS4j30XdhAC3lkeNO+XvpcuMklnZIJXgEMC4weNDs7KtOTkWDKzmNyHd5lczKWsWZNiXL2aaNZTTAS1RMhS1EjzupJWQ6Zivi8EWpoPs+iFJ45OHMLPJQ7J0KTvOdxyijw73aAbRC/vgJbEkNwCtDJYE0K5giWdFPKVAqKFjywhLGAi1Dd9u/HE1qMFBUe3+r56h4p7+dejo7+m8qbKxusqn6x98AfW47q3/+jdHuBRD4f1JlRdEA3JOkimwEqZi1aoRAMUfSIkajyNY3iMf4yXvu3bvednOC1qj2/HV+gzZNNzvS8BBQpF+yqhssyFjC+W6GVMdBStoGJlrhBFiEQtRqImuM7kZMmTAmk5xm/jlLu+tSFpVVsqoouDsYKX5zetjj6J41ZO+FzD9HcecktbGywa5iym9dVFzMW5mXeKmXXE5+wAz/gTOLNkFGVVxUWF0pBwsEpY8rtmuEBO/zCqExaY2Nsh4598ffyHZ2trL/zk8Mu/3hdyO7jq6Fbnmc70lJbjzt2nK/H33R/uc0z/7cKpC3+76tjzs5PdZ2oqJm+NnNny1vHatacJHyf9/41H0Y/gtFWv02JysTJtbIG+nMzLzs4jd4epoMCUarWSWVdAVX7KzoBf1FyTMS6seeQxWUsS9dNZ3xEqjJ15UMb8cPIr7xG9GvN/yqpgvySDgDwuWRYfRrtkSslbEfWKpMTkjWw5PJMwEB1OByJAVCCjYFV1z34wsf+DqfWNFz/YP/HBc/XfsHSfaW0+1ZOd3Xeque10VwYta7nsm7vucFzHzOWWy5i+4XDc8Hn9qO3Ae5M22+R7B9oO3nvKZnvqnuRJJ0Fj49BKiLiRccsMVHIyNhgEzY3XagXlBQ5F/QW7F7Sr4HF/HiY4VuLoacnhCgNZ+hgRTHl8Jyi8rn5Pyeq9Dt+v7+CPhz27rS1fGljrqxrApS37i3P3dPh+T+Edy/pOV4/9hHrluey+8pouE1H7lPbT3c2nWoK8S6es22tqR63PZSu7LrZNvukkJ2EBz/pd4D+CSDVUo5ErXRQlSNUkGD+kxlJObJaSAFpze/T7hw79YPRO8c61VTtt+BVG/vBvJ+/2tLx1omU0u2A/SCUdpHJOqkFAPxFNy6D6wKIhz+c6ekiCqXduUacfPidGB6gvRInGP5pLUxSZK9QtUm4WqFmYeO9Sw535GkX0H6wSWoJd0wpWCTMpVrHArmFdErzMOIxVftPL37lD/ZKszXQ+nGI9D59lumHdBKCSCFSIfwgip8rI5aqgIBlSazSUgqZcLKV4lNvn5ABT4p6gwDNjnAwlHtnZu77Eb1HGffiUL4HeR6X8Yu57rOnBD4WdmvY/qKG0sF2/H02ABfUzJYwBxf0FwZ7j/H+lt5Hcx+dgOCGafCb3Ie45+FHuI0SRf5D7hImKj203X6V+m70Fcp9LgwUaTeHARch9+rNuLi4drBJyn8iyHRsrB0oX05sf/JX90PupkPwUH7juGv5c8uPz2nZXQmJNLJO4/fdlUSgMbDPKqo6MkrmCZNiFVVJchiwCwphgkDFyKc+MIdXmi7ONLwzqCjhVlGVRXuOK33ivM1/b/mK9QnGOZUzNha7jxwPZupBbLYIz1YRR0SpInNF84hzQpYgvTNWPfT5TF9OxOdsXZepwGmdhN1msT2ZAxYh8pivR+pAaHAGN8aX1yJghxDiwmY+F+KElGorDZK5YmlYLzs8k7FjIQyKypDOxECuSal3+5vSi6pRNL42sO9hmntXnlBpG3asf0NaHd/HPqf4bhypTHc/2Uze9xeXtWdEbnwOdbgN7MIPn40gdFxqqiWJdNMdRmoBfSTeJFoEhf3qUx4sOkGiFHDPmuVL8cZMzOc9V69xvne3/1+fc7/YZKzuzfbvOn5+gIjqeGsgp226rPLRh93d3Or++3XrwwBOrfXYidWKNpvmvCZArysEdqdRqsAJqPlcUI/OCrwh48x2a945Qf/SGiZbt3XrpEnUCFF6gyCoWUlTKFI8bOZCTfLpo58RDMo65TxPvMO236TXkS0TgOwnIJwQ4fAtaCqIfjBzTMojAEikx+tZjMEvC3ad4F979M5/qjk8FLCVRP5sb9v6S0tEniScktcarwndX8IRwpmpKii9g3SSezjvCsMDngkwL/cnt038+9vQfj3yj4dymrnMNrGcu+fKHAwMfXqZ/Opfserqs7GkXoX0DHjuEPWuuoYAjlES24460FdA+IcrJc0D7tDBDjkrwr3AO6B+1IgzjdYL+AZZQ5ckQYKklrC6oLwArLwTjowEtJTnzA9CbeJSHllujtfGJHKTbCQnhZpNpWZArKEgZzj76FhAWKDoKzIH481lF4vkoi2BiAbUORAQBGx9+0rkvP3t4/dqxotnh9w89eXfQvOXVsUuXjlzvM5bs/Wpn+1fGy2aL9jY27i6qOtJGmwu2lja4clcPVw1d72+9MZm1t79k6VDh4MGC7kuD2Zk955xVrvy8HRs3bs8hEqyF09kGu8lBnDVEZQjJTEszKl2xkZEhdMDsTIGvT+AF/+7XJ3oB95JJTnPVh3v6/2VPoe3g9eHL/77jtu34QM+hguT6/c173tieU3bozW1d7zzffju3a7+t62g5Hjavs+Ym6tZ1P9nYeHLLqr33XHX7ytdsLk6ttGbG8eu3HG60n+zOyh5+eaByi02f3QvcGyiOCqZuwPkrpmkKmSTlpoJ9sdSN8+cBToztdfAptBBz4q1BjEajDJK55BA6qXCUT1IHKXR2id8SLdjMQ4t+fe731F+9GVupb4/WeRPOnz9Pc3Plk/TVCxeEysnnoP/0eBQR6yYm2CV8BpuPIlnmsH+icsoMfXVuKHf4+e7u5wasGrV1YKpn0/NDeRBFBipbdldEqk0VfbaqwdLFPger+sEDAz39RbXTicH8moNQO/XWp1mHwPoo/y1fJW6G8w2D6Av2FyQLcUVpEWHwe4EKX7S/5KyA7S1IMk/fzN/bHlcUgyNWhi/LTojItmRmZ2dasqFAKel0l6rkzzBsYmEW++F8pUIjp6+R/k+QTARahtaAHwpZmaR25S6Su4JhbWFlY7okm3nbn1/8nxFVxVdHvn84+9ypNGfxM+VN46XepXlDlzofVZzOqeG8WX0JVJw7SiPVKaW9UHGW6IHlj098p4+vtw3WWQv3t9FrfN/6/5ef4BWEb2yCV1BIXqFN9AorZAGvAFhCPGU/BSylEN9sTobgLIf49qroOTBaDjjvgy6q0SJrsJxRYQbqOBl4Q9WCkqYgIgJyHZ6moULCqt//6ae+S3jgxw8efID7fc9D/TmK3d5PvB/hs77N1BIqmkhcB4/7kCmEokiolkDisbIYlSsiMpAwoHxB4vmfzxiEhIGEAfzkrOPqrjJ3OZe6s2ys72PvN+jXZpnzu19t4hddDNdv6W87fpyUZ7CLZ0EeqeBWl5Ev4MlKJZUQFxcRBLkbI+7CFKgokyMgEaXJco98W7JZ+gApZFEy3Pl0OfU779UVS3fXdL2wdVWO67XtTVO7q1UeTdn2tYXdtiRDZb+ttZ26ZqD+7YpvJGZpyfgbQ32eg2VpXee664ZzUtfvqioZbUpLJ5Vxn/937EH2W6DrPLKgUlSJeGtYeXolm1e8LD0mWMeyrvQgQf/eTQ99N136FlNvCfjiKEkbswLf5SwBf43/CZwInIz7yg61tE2UlU60th4uO8KXZWbaFvOlmZZSnsp9NHSoXBgqhaEsGLrvzemlvs1UVtdP1tVN1lfXktel6tQ6s7kutdpUbzbXz9WsrSPQOvH1wtpUgNaZ1poIDl398HghCB+0UMigBF1NlnR1vair8RDnXgjoqvBtXcCSSVgNAhZeoV4Q5ywQ/2vhnEk2ASdNy+UyimKVGpeaFU86PMeUA2WX6HKxGTSd5BO1D39NHT33kq+W2jeLPzk/QP/Z95G3jb4rhGIhS5HVQQuSftBX8o1MHsyqFS4Ng+TChzrp31CIZyLpBWT+kKpg8u89v3kTf4w/esvrOe3d/rL2Nsu8fBtKi1bmS4T03KT3PRLvqWxiERuA913CesTrQ2QTvD5FvD4l/VNN2N9z/MyuOQN9c25kjD6yo26uBcog5vCDj06yOuFfaSZA+xPYqyiT8B68Inbx4hU0Ylwrgua/pQgZljnqsepYUnfyMY5+LNSTknoJnR8aeubuiDm1pivLuqlkia6ws7h6olHWEVy97UTNwKXutNxtXx0a9YzkrrmAQ9mrU+3P3+3+sfOZ7ow0+67ygp3tWZU7S/Hw812muqeuNPe8MVnlfOlu94Zn8dI/Cd9RGX8vfYH8DwGIkhQtREkniXAX5rZAjBS/szYKMVJzbf4blZRFNc6KH6MInd3Mh1S8UDOoruJxhEyL7sMxgbva/c1f+P6b+RAbfB9KeHQ++x9QuydbIwCAVeHWkEVl4ex4UFBwcAz5cmU2mU2LQu+TLMkMeXZBjGBWgpCikjNEnwHWRX1zb65ztbkwI2f58py9OR2rjAW5a5Yuz2X/Q10+uCohKcFqkpUP5UOjgD6KNuE5WK0b9TJH0SuMHrVTl5CSWYNamZVwn0QtzBZ0jLqOjjHNaIB5Ah3F/4kuMn9Ar7BW9Ao+gxKYg6hdzqAjAD9OnURPsRr0Cv1LpKfvoWjWgnZQ8egksw9dYfejMWYO1tiMLMxdlM6sAxrX4M5GCfhPaILQpt5Dq5ledAw/RGeZPvQUzGtj+kU85nsohF0JOCnohkCL8LMPtTO3US2ViQz0/yA77KEdf+K/BbScAd4BvpwZQjrAfZb9CPUJdMn+9iGLjPDzPtoA7Qn6ImJg3YvUAbSbvot2WysunD939vChiScPHtg/vu+JvXt279q5Y2x0+8g219bhocGB/i2b+3p7urs2dXY4He1trS0bm+1NG9Y3NtTX1qxbW11VWVFeVmpbyoWqlCvwtFpVxBd1qVJWoGmVGprqlBXYIyvyyAWgZ51R57HWNukr65pKirV6vV3L6z1WD5NUQm7nJndnYMAOJGAWzAUSlfV8ZW1zk67E7RAGAdLwWE8cz54fk1oeqqihyWMzQm9Bv1Toz3fLPjNcHhjmdR5U43ZvmkZ0EsCt2mksNNiiI3bYiZ33dBh5Pd/UBbjTCqTRNziKoKUJtLCuFCjqZkJRB9ydG/gZLLWamzw6R7e9DLARleQRrvoZZOF3iG2HR9ep03lkSXxHTZNb78EOXiv165pAYtipdet5vc5un/HfiSfYvB5oUahwmseTtdNWPFnf3ARLeXSTDU1XKUwVOQrt00tgrGlGhzxWAUoRKAGSjo50UCWGk7lKKQR87YwVecaFUUYACP1O2IUAE5FmrWDVnTOUCAsVFzKQhWCEghFGHLEGsBmAKUTYuIi9VMJWwEgoGZlFFEYeYVD8gZTgZKwq1qqwKq0aKoiCsyCgqwC5iRFSYvS6Bgdh7TTQrBPAM3h8WmnVzgiU6iTMccAksPF5GHBO0BYQgvXEjTc+2kFjc9PrGgT0hSdgFJJfyoqSaWqtkX+k1rVNcHol03it0QGqTbp0UokO1NpjrW8iuA4t6Dxod3HKCqJduia+S8vbpyMj3cMlQIafdsoMDqNbVDKiWnxoLigmnVTeydscBAMMBa5yAHWu1zk8HQ4jNHWhNreN6IGTYKNo8OVJ05hJwmvQGpCUTONR8V2FHjVfOD+Sj/LFERkZkfOFHhwtyrmEL9HF9rk7+Q7QOWtNU4+22+4E2h4r7/QwfKF2mkGFYCGxGDZRMo3WGmE3laB164w1G8EsyfZ1bnexbtrKGJydTtIv1oOlu6UhvrjYvmBGic7tsTo7HYBRYheQwfYAWMI7dZtArrBdkFU9T/7zSjOZ09Dc5NZs4jfxIFOr1e2EbWt1nXat294pyBjmA2soZQX7yB9J7ogiVp7U2Q0PMIQOB98hAog9fhbW81lAN2AthPEVZDnhjYW3u4Iv2QQY5HZu8tCgY3rdJruoJKhG8BR/FwkvQNLBmQrE3aF5gR6WetCBy+3pebzbO9+1kdsBUksVdcXDGIiuNek9m7WefrtxHsXpGe/QuXWhfC5PHsLkUnI7PCw0xjudxB3JiO4BoAIAuqYO0F4gaHO4AxoH0xjD/EqeQeNjJMGJ4gZYmkoi2/GM1+gcdp3DAVCwF71W52Hhret2EuUijrZG3E8NeHt4Od31MBcRk9F65ODzu51dvB78s4eYqSh9wiMD3KH6Jg/Sut2824OBxSQbIAN5g0dmKCcvuIaNvLMLDpGsp3N2CXNtwK4gHUJNW8Lr7YBCJQmyBMGBf+ggj043aKOnFayNTQpzh7t1OW7wU63gYhlD53oHBAJdqM6mE47aCZpMhFBOenYgJCIqkwgizBcug2fAON0qT3oEEa4ho4isEKgCZ3VNnpoAily4oLHV6KFismGQbB7XQTxhhIMiwmOTykG8VtAqLZmt81ANTdLxCPPLyVRt4MDEaQARHC0JhPoAv2qRX3FRmXBphEuZ5FEkwUF7GOBBHJaT7TxSAmgD0+IcWmBX3AC0YSmdNCJsxCF1mKQuYU9iANQRhwmpgZMnt3bGf7sGIrCDJ7fdTpZXCAuRGQJpt0iYiEtGBr9IFNJK4qUmV7mwhYVglXDJBZ7JmLgl9nHBS9IDriTJ6aUf0Rmyy8OSVUp216X19NqNm8RZMsmD68CjgufurBXyi41gDbxeDn4Mtg9WpfPUGyFsCHs7LEq1QvQORCuxjUc20CGpgaKRB/FlmDwQmBZf5qGgO9/ir1IIK/hs8lLy2dMUloO3J84oNEgDjt7d6dgkhmaQMsrWriLJkEw4aKVwtqPENTU0sVrGLqiMwTNmlLRYfI4a58fHiE3KA5JUkDH3/CArkBsTdcMgPUeNii+c5Vb8c4sppNP0KIUx4o0Min+8FC0eUIV4XBWUSLlC9BMVxKbdbuLapluDiYVqDGEADwfWcoDJHIlLkM0eYKWGLK0QIEIXzE1O2BGPLUkNA6GAe0dUbTUMhgI3d7QiFlwzfr/At4gtCgH4ViWJei4NS7NF7Rwz2qFlI7cDUGzklixJLVmp5jNeXyIvnqny8UF+nhgJ9Pw8RdKbxhrIehktCysadKEgrlxBngZgFfru3GksN0gILEGgknLdbnXA/xP3P4uQFQnpJLK7Pwvw7IXzgLMO+uIRxWehQQJYOuWg+TcBSuagKvKoi0j+QmKTkihAKpzv3m9JPkdIJxYIRgARU1wIjSWylwdcwpAxMDcgt27BpKW5n4E2NO0FKJHUt0gk8WB4swY9ubVEdMJqRMeHjFJqu5ec7gGB3AGjTtcHeVYRhmwLAmUfCVU6gq0wCE7ODQlPn9Mp+CGhcImFXKqO5MOQ8/OhOrwKrRLLH16qLCAGMElNq7Q5dqgkZvy/jbeLroqCIA93g1unCw2DIbcuHEoLz4QgXmmMF2AQxWUGCYvsYAKMU8Qj3Gsod2U9CIHUYKpsrYrUdYGS6rzxHw3ryHzwUjOol9+hJ7KYQW38TkgXiniPTtcCThFC/Qyqjre73RBS3Typn9Y3iU8yiGfQyniSH5BcZh4/IR6qs4UATTxRPOeM/0o8KZUerbt/ft0xWJe03IGFZ1DPFy5LVA5vFBUPLmEvMwiiMS8ywhiktd0t7mYoEGEwkSwv8UP6wfF2gQowdIYw9P8A39YnewplbmRzdHJlYW0KZW5kb2JqCnhyZWYKMCAyNgowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMTE3MTMgMDAwMDAgbiAKMDAwMDAxMTc3NyAwMDAwMCBuIAowMDAwMDExNjUxIDAwMDAwIG4gCjAwMDAwMTE2MzAgMDAwMDAgbiAKMDAwMDAwMDMwMyAwMDAwMCBuIAowMDAwMDAwMTc1IDAwMDAwIG4gCjAwMDAwMDAwNjUgMDAwMDAgbiAKMDAwMDAwMDAxNSAwMDAwMCBuIAowMDAwMDA5NjgzIDAwMDAwIG4gCjAwMDAwMTE0ODEgMDAwMDAgbiAKMDAwMDAwNzU2OSAwMDAwMCBuIAowMDAwMDA3NDUwIDAwMDAwIG4gCjAwMDAwMDczMzcgMDAwMDAgbiAKMDAwMDAwODY0OSAwMDAwMCBuIAowMDAwMDA4NTYxIDAwMDAwIG4gCjAwMDAwMDg1ODcgMDAwMDAgbiAKMDAwMDAwODYxMyAwMDAwMCBuIAowMDAwMDExODI0IDAwMDAwIG4gCjAwMDAwMDg3MjUgMDAwMDAgbiAKMDAwMDAwODk5MiAwMDAwMCBuIAowMDAwMDA5MzUzIDAwMDAwIG4gCjAwMDAwMTYxMTYgMDAwMDAgbiAKMDAwMDAwOTgzMCAwMDAwMCBuIAowMDAwMDEwMDk4IDAwMDAwIG4gCjAwMDAwMTEwMzAgMDAwMDAgbiAKdHJhaWxlcgo8PAovU2l6ZSAyNgovUm9vdCAzIDAgUgovSW5mbyAxNCAwIFIKL0lEIFs8ZDlmZjdiM2E4OTcwMmY1NTE2ZGRjODMyZmFlNGM2OTk+IDxkOWZmN2IzYTg5NzAyZjU1MTZkZGM4MzJmYWU0YzY5OT5dCj4+CnN0YXJ0eHJlZgoyNDgzMgolJUVPRgo=";

  const opcionTarjetas = {
    iconStyle: "solid",
    style: {
      base: {
        iconColor: "#162234",
        color: "#000",
        fontWeight: 500,
        fontFamily: "sans-serif",
        fontSize: "16px",
        fontSmoothing: "antialiased",
        ":-webkit-autofill": { color: "#000" },
        "::placeholder": { color: "#000" },
      },
      invalid: {
        iconColor: "#162234",
        color: "#D83A18",
      },
    },
  };

  let fechaInicial = new Date(Date.now());
  fechaInicial.setDate(fechaInicial.getDate() + 1);
  let segundaFecha = new Date();
  segundaFecha.setDate(segundaFecha.getDate() + 4);
  const initial = {
    idReserva_res: 0,
    idCliente_res: 0, //userContext.usuario.idTercero_ter,
    FechaInicio_Res: fechaInicial.toISOString().split("T")[0],
    FechaFin_Res: segundaFecha.toISOString().split("T")[0],
    idVehiculo_res: vehiculo.idVehiculo_veh,
    estado_res: "A",
    costoPorDia_fac: vehiculo.CostoPorDia_veh,
    idRecepcionOnline_fac: "",
    Nota_Res: "Local en Santiago",
    Hora_res: "08:00",
    idPersonal_res: 0,
  };

  const MySwal = withReactContent(Swal);
  const [valor, setValor] = useState(1);
  const [formValues, setFormValues] = useState(initial);
  const [formErrors, setFormErrors] = useState({});

  let diferenciaDias = 0;
  const lugares = [
    { Nota_Res: "Local en Santiago" },
    { Nota_Res: "Aeropuerto Internacional de las Américas" },
    { Nota_Res: "Aeropuerto Internacional del Cibao" },
    { Nota_Res: "Aeropuerto Internacional de Punta Cana" },
    { Nota_Res: "Aeropuerto Internacional de las Américas" },
  ];
  const handleInputChange = (e) => {
    const { id, value, type } = e.target;
    if (id.includes("id"))
      setFormValues({ ...formValues, [id]: parseInt(value) });
    else if (id.includes("Fecha")) {
      const dateValue = new Date(value).toISOString().split("T")[0];
      setFormValues({ ...formValues, [id]: dateValue });
    } else setFormValues({ ...formValues, [id]: value });
  };

  useEffect(() => {
    const date1 = new Date(formValues.FechaInicio_Res);
    const date2 = new Date(formValues.FechaFin_Res);
    date1.setDate(date1.getDate());
    date2.setDate(date2.getDate());
    const diffTime = Math.abs(date2 - date1);
    diferenciaDias = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

    if (diferenciaDias < 0) {
      setValor(1);
    } else {
      setValor(parseFloat(formValues.costoPorDia_fac) * diferenciaDias);
    }
  }, [formValues.FechaInicio_Res, formValues.FechaFin_Res]);

  const guardar = document.getElementById("guarda");

  function convertirFormatoFecha(fecha) {
    const partesFecha = fecha.split("-");

    const fechaConvertida = `${partesFecha[2]}/${partesFecha[1]}/${partesFecha[0]}`;

    return fechaConvertida;
  }

  const generarPDFBase64 = () => {
    return new Promise((resolve, reject) => {
      const documentoDefinition = {
        content: [
          {
            text: "CONTRATO DE RESERVA",
            fontSize: 18,
            bold: true,
            margin: [0, 0, 0, 20],
            alignment: "center",
          },
          {
            text: [
              `
            Este contrato se establece entre RRRentalesRD, en adelante denominado "El Proveedor", y ${
              userContext.usuario.Nombre_ter
            }, en adelante denominado "El Cliente".
          
          1. OBJETO DEL CONTRATO:
          El Proveedor se compromete a ofrecer el servicio reservado, descrito como: renta de vehículos.
          
          2. FECHA Y DURACIÓN:
          El servicio se ofrecerá desde el ${convertirFormatoFecha(
            initial.FechaInicio_Res
          )} hasta el ${convertirFormatoFecha(initial.FechaFin_Res)}
          3. RESPONSABILIDADES DEL CLIENTE:
          El Cliente se compromete a:
          - Solamente la persona cuyo nombre aparezca en el contrato y a quien se alquile el vehículo será el conductor. El permitir que cualquier persona maneje el vehículo cancelará todo seguro y hace que el que alquiló el vehículo se responsabilice por todos los gastos de daños al vehículo y días de reparación.
          - El vehículo no podrá ser usado en carreras o competencias, no se usará para enseñar a conducir, no se usará como taxi, nunca se usará para empujar o remolcar otros vehículos, además de que solo será usado en carreteras asfaltadas.
          - El consumo de gasolina será cubierto por el cliente.
          - El vehículo será devuelto en el día y hora especificado en el contrato, en la oficina de la compañía. El incumplimiento hará necesario que la policía recoja el vehículo y será motivo para que el vehículo sea devuelto de inmediato a la oficina de la compañía.
          - El cliente no tiene autorización para contratar gastos de reparación de ninguna clase al vehículo.
          - En caso de accidente, el cliente notificará de inmediato a la compañía y a la policía, procediendo a levantar una acta policial.
          - El impuesto del 5% del gobierno para negocio del alquiler de vehículos se añadirá a cada factura.
          - La cantidad mínima de renta será de 3 días.
          - Si la persona cambia de dirección en la República Dominicana, deberá informar de inmediato a la oficina de la compañía.
          - Las cancelaciones de las reservaciones se cobrarán 1 día y lo demás será devuelto en la forma de pago que realizó.
          - El cliente devolverá el vehículo en las mismas condiciones en que le fue entregado.
          - La compañía pone seguro de ley a todos sus vehículos.
          - Cualquier multa será informada a la compañía y cancelada al cerrar el contrato.
          - En caso de incumplimiento del contrato podrá ser reportado a Data Crédito.
          - El vehículo nunca será conducido hasta que haya pasado un mínimo de 12 horas después de ingerir bebidas alcohólicas, sin importar la cantidad consumida.
          - Cumplir con todas las políticas y normas establecidas por El Proveedor.
          - Pagar el monto acordado por el servicio en la fecha establecida.
            
          4. CANCELACIONES Y MODIFICACIONES:
          - Cualquier cancelación o modificación debe notificarse con al menos 2 días de anticipación. 
          - Las cancelaciones realizadas estarán sujetas a un cobro de por lo menos un día del costo de la renta del vehículo en cuestión.
          
          5. INDEMNIZACIÓN:
          En caso de incumplimiento de las cláusulas de este contrato por parte de El Cliente, El Proveedor tiene el derecho de buscar reparación por daños y perjuicios.
          
          6. LEY APLICABLE:
          Este contrato se regirá y se interpretará de acuerdo con las leyes vigentes de la República Dominicana.
          
          Ambas partes, al firmar, aceptan todos los términos y condiciones descritos en este contrato.
              `,
            ],
            alignment: "justify",
          },
        ],
        footer: function (currentPage, pageCount) {
          if (currentPage === pageCount) {
            return {
              columns: [
                {
                  text: "__________________________\nFirma de El Proveedor\n\nFecha: ______/______/________",
                  alignment: "center",
                  fontSize: 10,
                  margin: [0, 0, 0, 10],
                },
                {
                  text: "__________________________\nFirma de El Cliente\n\nFecha: ______/______/________",
                  alignment: "center",
                  fontSize: 10,
                  margin: [0, 0, 0, 10],
                },
              ],
              margin: [10, 10],
            };
          } else {
            return "";
          }
        },
      };

      pdfMake.createPdf(documentoDefinition).getBase64((base64) => {
        resolve(base64);
      });
    });
  };

  const enviarEmail = (prueba) => {
    //puerto:2525
    Email.send({
      Host: "smtp.elasticemail.com",
      Username: "quitomiguel56@gmail.com",
      Password: "EAC635C56878709AEA14A25537D4F24BEAF9",
      To: userContext.usuario.correo,
      From: "quitomiguel56@gmail.com",
      Subject: "Recibo de reservación",
      Body: "Confirmación de reservación de vehículo adjuntada",
      Attachments: [
        {
          name: "recibo.pdf",
          data: prueba,
        },
        {
          name: "contrato.pdf",
          data: contrato,
        },
      ],
    });
    console.log("enviado");
  };
  const handleSelectChange = (e) => {
    const { id, value } = e.target;
    const selectId = id; //
    const optionId =
      e.target.options[e.target.selectedIndex].getAttribute("data-key");
    if (selectId == "idVehiculo_res")
      matricula = e.target.options[e.target.selectedIndex].value;
    if (selectId != "Nota_Res") {
      setFormValues({
        ...formValues,
        [selectId]: parseInt(optionId),
      });
    } else {
      setFormValues({
        ...formValues,
        [selectId]: optionId,
      });
    }
  };
  const validarForm = async () => {
    let fechaValidada = true;
    const errors = {};
    if (formValues.idVehiculo_res == "" || isNaN(formValues.idVehiculo_res)) {
      errors.idVehiculo_res = "Debe especificar el vehículo";
      fechaValidada = false;
    }
    if (formValues.idCliente_res == "" || isNaN(formValues.idCliente_res)) {
      errors.idCliente_res = "Debe especificar el cliente";
      fechaValidada = false;
    }
    if (formValues.idPersonal_res == "" || isNaN(formValues.idPersonal_res)) {
      formValues.idPersonal_res = 0;
    }
    if (formValues.FechaInicio_Res == "") {
      console.log("Debe especificar la fecha inicial");
      errors.FechaInicio_Res = "Debe especificar la fecha inicial";
      fechaValidada = false;
    }
    if (formValues.FechaFin_Res == "") {
      console.log("Debe especificar la fecha final");
      errors.FechaFin_Res = "Debe especificar la fecha final";
      fechaValidada = false;
    }
    if (fechaValidada) {
      const dateActual = Date.now();
      const date1 = new Date(formValues.FechaInicio_Res);
      const date2 = new Date(formValues.FechaFin_Res);
      date1.setDate(date1.getDate());
      date2.setDate(date2.getDate());
      const diffTime = Math.abs(date2 - date1);

      diferenciaDias = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
      if (diferenciaDias > 90) {
        errors.FechaFin_Res =
          "No es posible rentar un vehículo por más de 90 días";
      }

      if (date2 < date1) {
        errors.FechaFin_Res =
          "La fecha de fin no puede ser anterior a la inicial";
      }

      if (date1 < dateActual || date1 == dateActual) {
        errors.FechaInicio_Res =
          "La fecha de inicio no puede ser anterior a la actual";
      }

      if (diferenciaDias < 3) {
        errors.FechaFin_Res = "Menor de 3 días no es posible";
      }
      setValor(parseFloat(formValues.costoPorDia_fac) * diferenciaDias);
      const res = await pagoTarjeta("reserva/disponible", {
        inicio: date1.toISOString().split("T")[0],
        fin: date2.toISOString().split("T")[0],
        id: formValues.idVehiculo_res,
      });
      const resP = await pagoTarjeta("reserva/disponiblePersonal", {
        inicio: date1.toISOString().split("T")[0],
        fin: date2.toISOString().split("T")[0],
        id: formValues.idPersonal_res,
      });
      if (res.estado_veh == 1) {
        errors.FechaInicio_Res = "Vehículo no disponible en esta fecha";
      }
      if (resP.estado_veh == 1) {
        errors.idPersonal_res = "Personal no disponible en ese momento";
      }
      formValues.FechaInicio_Res = date1.toISOString().split("T")[0];
      formValues.FechaFin_Res = date2.toISOString().split("T")[0];
    }
    //contrato = generarPDFBase64();
    return errors;
  };
  const handleGuardar = async (e) => {
    e.preventDefault();
    const error = await validarForm();
    setFormErrors(error);
    MySwal.fire({
      icon: "info",
      title: "Realizando reserva",
      text: "Esperando respuesta del servidor...",
      allowOutsideClick: false,
      showConfirmButton: false,
      willOpen: () => {
        MySwal.showLoading();
      },
    });
    if (Object.keys(error).length == 0) {
      const { error, paymentMethod } = await stripe.createPaymentMethod({
        type: "card",
        card: elements.getElement(CardElement),
      });

      if (!error) {
        try {
          const { id } = paymentMethod;
          const res = await pagoTarjeta("reserva/pagoTarjeta", {
            amount: valor * 100,
            id,
          });
          if (res.id) {
            console.log("Se recibió el pago");
            formValues.idRecepcionOnline_fac = res.id;
            console.log(formValues);
            await addData("reserva", formValues);
            let dataCorreo = {
              customize: {},
              images: {
                logo: "https://static.vecteezy.com/system/resources/previews/000/623/239/original/auto-car-logo-template-vector-icon.jpg",
              },
              sender: {
                company: "RR RENTALS RD",
                address:
                  "Autopista Duarte #10 Reparto los Garcia Al lado de Torre Real 2",
                zip: "5100",
                city: "Santiago de los caballeros",
                country: "República Dominicana",
              },
              client: {
                company: userContext.usuario.Nombre_ter,
                address: formValues.Nota_Res,
                zip: userContext.usuario.Telefono_ter,
                city: "",
                country: "",
              },
              information: {
                number: id,
                date: formValues.FechaInicio_Res,
                "due-date": formValues.FechaFin_Res,
              },
              products: [
                {
                  quantity: 1,
                  description: nombreProducto,
                  "tax-rate": 0,
                  price: valor,
                },
              ],
              "bottom-notice":
                "Este documento certifica que la reservación fue hecha de manera correcta",
              settings: {
                currency: "USD",
              },
              translate: {
                invoice: "Factura",
                number: "Número",
                date: "Fecha de inicio de reservación",
                description: "Descripción",
                "due-date": "Fecha de fin de reservación",
                products: "Productos",
                quantity: "Cantidad",
                price: "Precio",
                "product-total": "Precio total de productos",
                total: "Total",
              },
            };
            console.log(dataCorreo);
            await easyinvoice.createInvoice(dataCorreo, function (result) {
              enviarEmail(result.pdf);
              console.log("Se envió el correo");
            });
            props.onHide();
            MySwal.close();
            MySwal.fire({
              icon: "success",
              title: "Reserva hecha de manera satisfactoria",
              confirmButtonText: "Aceptar",
            });
          }
        } catch (error) {
          console.log("Error: " + error);
        }
      } else {
        MySwal.close();
      }
    } else {
      MySwal.close();
    }
  };
  const [clientes, setClientes] = useState([]);
  useEffect(() => {
    const fetchData = async () => {
      try {
        const data = await getAllData("personal/cliente");
        setClientes(data);
      } catch (error) {
        console.log(error);
      }
    };
    fetchData();
  }, []);
  const [empleados, setEmpleados] = useState([]);
  useEffect(() => {
    const fetchData = async () => {
      try {
        const data = await getAllData("personal/empleado");
        setEmpleados(data);
      } catch (error) {
        console.log(error);
      }
    };
    fetchData();
  }, []);
  return (
    <Modal
      {...props}
      size="ls"
      aria-labelledby="contained-modal-title-vcenter"
      centered
    >
      <Modal.Header closeButton>
        <Modal.Title id="contained-modal-title-vcenter">
          Realizar reserva
        </Modal.Title>
      </Modal.Header>
      <Modal.Body>
        <div className="container">
          <form>
            <div>
              <label
                className="block text-gray-700 text-sm font-bold mb-2"
                htmlFor={"idCliente_res"}
              >
                {"Cliente"}
              </label>

              <select
                key={"nose"}
                className="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id={"idCliente_res"}
                onChange={handleSelectChange}
              >
                <option data-key={""}>Seleccione un valor</option>
                {clientes.map((values, index) => {
                  const key = values["idTercero_ter"];
                  const descripcion =
                    values["Nombre_usu"] + " : " + values["Nombre_ter"];
                  return (
                    <option key={index} data-key={key} value={descripcion}>
                      {descripcion}
                    </option>
                  );
                })}
              </select>
              <p className="text-red-700 text-sm font-bold mb-2">
                {formErrors.idCliente_res}
              </p>
            </div>
            <div>
              <label
                htmlFor={"FechaInicio_Res"}
                className="block text-gray-700 text-sm font-bold mb-2"
              >
                {"Fecha de inicio"}
              </label>
              <input
                className="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                type={"date"}
                id={"FechaInicio_Res"}
                name={"FechaInicio_Res"}
                placeholder={"Seleccione la fecha inicial"}
                onChange={handleInputChange}
                value={formValues.FechaInicio_Res}
                required
              />

              <p className="text-red-700 text-sm font-bold mb-2">
                {formErrors.FechaInicio_Res}
              </p>
            </div>
            <div key={"FechaFin_Res"}>
              <label
                htmlFor={"FechaFin_Res"}
                className="block text-gray-700 text-sm font-bold mb-2"
              >
                {"Fecha de fin de reservación"}
              </label>
              <input
                className="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                type={"date"}
                id={"FechaFin_Res"}
                name={"FechaFin_Res"}
                placeholder={"Seleccione su fecha de nacimiento"}
                onChange={handleInputChange}
                value={formValues.FechaFin_Res}
                required
              />

              <p className="text-red-700 text-sm font-bold mb-2">
                {formErrors.FechaFin_Res}
              </p>
            </div>
            <div key={"Hora_res"}>
              <label
                htmlFor={"Hora_res"}
                className="block text-gray-700 text-sm font-bold mb-2"
              >
                {"Hora de entrega"}
              </label>
              <input
                className="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                type={"time"}
                id={"Hora_res"}
                name={"Hora_res"}
                value={formValues.Hora_res}
                placeholder={"Seleccione la hora de entrega"}
                onChange={handleInputChange}
                required
              />
            </div>
            <div key={"Nota_Res"}>
              <label
                className="block text-gray-700 text-sm font-bold mb-2"
                htmlFor={"Nota_Res"}
              >
                {"Lugar de entrega"}
              </label>

              <select
                key={"nose"}
                className="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id={"Nota_Res"}
                onChange={handleSelectChange}
              >
                {lugares.map((values, index) => {
                  const key = values["Nota_Res"];
                  const descripcion = values["Nota_Res"];
                  return (
                    <option key={index} data-key={key} value={descripcion}>
                      {descripcion}
                    </option>
                  );
                })}
              </select>
              {/* <p className="text-red-700 text-sm font-bold mb-2">
                {formErrors.idCliente_res}
              </p> */}
            </div>

            <div>
              <label
                className="block text-gray-700 text-sm font-bold mb-2"
                htmlFor={"idPersonal_res"}
              >
                {"Entregar por"}
              </label>

              <select
                key={"nose"}
                className="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id={"idPersonal_res"}
                onChange={handleSelectChange}
              >
                <option data-key={""}>Seleccione un valor</option>
                {empleados.map((values, index) => {
                  const key = values["idTercero_ter"];
                  const descripcion =
                    values["Nombre_usu"] + " : " + values["Nombre_ter"];
                  return (
                    <option key={index} data-key={key} value={descripcion}>
                      {descripcion}
                    </option>
                  );
                })}
              </select>
              <p className="text-red-700 text-sm font-bold mb-2">
                {formErrors.idPersonal_res}
              </p>
            </div>

            <div>
              <label className="block text-gray-700 text-lg font-bold mb-2">
                Valor de la reserva: ${valor}
              </label>
            </div>
            <div className="py-2">
              <CardElement options={opcionTarjetas} />
            </div>

            <div className="flex justify-end py-4">
              <button
                className="flex-shrink-0 bg-teal-500 hover:bg-teal-700 border-teal-500 hover:border-teal-700 text-sm border-4 text-white py-1 px-2 mx-2 rounded"
                type="submit"
                onClick={handleGuardar}
                id="guardar"
              >
                Pagar
              </button>
            </div>
          </form>
        </div>
      </Modal.Body>
      <Modal.Footer></Modal.Footer>
    </Modal>
  );
};

export default ReservaPopUp;
